export default {
  login: "trobinson41",
  id: 7894880,
  node_id: "MDQ6VXNlcjc4OTQ4ODA=",
  avatar_url: "https://avatars.githubusercontent.com/u/7894880?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/trobinson41",
  html_url: "https://github.com/trobinson41",
  followers_url: "https://api.github.com/users/trobinson41/followers",
  following_url:
    "https://api.github.com/users/trobinson41/following{/other_user}",
  gists_url: "https://api.github.com/users/trobinson41/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/trobinson41/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/trobinson41/subscriptions",
  organizations_url: "https://api.github.com/users/trobinson41/orgs",
  repos_url: "https://api.github.com/users/trobinson41/repos",
  events_url: "https://api.github.com/users/trobinson41/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/trobinson41/received_events",
  type: "User",
  site_admin: false,
  name: "Timothy Eric Robinson",
  company: "Contractor",
  blog: "theevolvingnaturalist.com/",
  location: "La Mesa, CA",
  email: null,
  hireable: null,
  bio: "Coder and technical writer",
  twitter_username: null,
  public_repos: 31,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2014-06-15T15:20:36Z",
  updated_at: "2021-03-29T19:13:40Z",
};
